version: '3.4'

services:
  authenticationserver:
    image: embe2/authenticationserver:0.1
    build:
      context: ./Spike.AuthenticationServer.IdentityServer
      dockerfile: Dockerfile
      args:
        VCS_REF: 31849378
        BUILD_VERSION: 0.1