version: '3.4'

services:
  spikemssql:
    image: embe2/spikemssql:0.1
    build:
      context: ./EFCoreSpike5
      dockerfile: Dockerfile
    depends_on:
      - ms-sql
    networks:
      - spikemssql-net
  ms-sql:
    image: microsoft/mssql-server-linux
    container_name: spikemssql-database
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "Password123!"
    ports:
      - "1433:1433"
    volumes:
      - type: volume
        source: spike-database
        target: /var/opt/mssql
    restart: no
    networks:
      - spikemssql-net
volumes:
  spike-database:
networks:
  spikemssql-net:
    driver: bridge